/**
 * orot-ui icon catalog
 * lucide-react 아이콘을 카테고리별로 재-export.
 * 직접 lucide-react를 import해도 무방하지만,
 * 이 파일을 통하면 프로젝트 내 사용 아이콘을 한 곳에서 관리할 수 있다.
 */

// ── General UI ──────────────────────────────────────────────────────────────
export {
  Search,
  X,
  XCircle,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronsLeft,
  ChevronsRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  MoreHorizontal,
  MoreVertical,
  Menu as MenuIcon,
  SlidersHorizontal,
  Settings,
  Settings2,
  Maximize2,
  Minimize2,
  ExternalLink,
  Link,
  Copy,
  Clipboard,
  ClipboardCheck,
  Eye,
  EyeOff,
  Filter,
  SortAsc,
  SortDesc,
  RefreshCw,
  RotateCcw,
  Loader,
  Loader2,
  CircleDot,
} from 'lucide-react';

// ── Actions ──────────────────────────────────────────────────────────────────
export {
  Plus,
  PlusCircle,
  Minus,
  MinusCircle,
  Edit as EditIcon,
  Edit2,
  Edit3,
  Pencil,
  Trash,
  Trash2,
  Save,
  Download,
  Upload as UploadIcon,
  Share,
  Share2,
  Send,
  Forward,
  Reply,
  Undo,
  Redo,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
} from 'lucide-react';

// ── Status / Feedback ─────────────────────────────────────────────────────────
export {
  Info,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Ban,
  ShieldAlert,
  ShieldCheck,
  HelpCircle,
  Bell,
  BellOff,
  BellRing,
  Star,
  StarHalf,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
} from 'lucide-react';

// ── File & Media ──────────────────────────────────────────────────────────────
export {
  File,
  FileText,
  FileImage,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Folder,
  FolderOpen,
  FolderPlus,
  Image as ImageIcon,
  ImageOff,
  Video,
  Music,
  Paperclip,
  Archive,
  Package,
} from 'lucide-react';

// ── Communication ─────────────────────────────────────────────────────────────
export {
  Mail,
  MailOpen,
  MailCheck,
  MessageSquare,
  MessageCircle,
  MessageSquarePlus,
  MessagesSquare,
  Phone,
  PhoneCall,
  PhoneOff,
  AtSign,
  Hash,
} from 'lucide-react';

// ── Navigation ────────────────────────────────────────────────────────────────
export {
  Home,
  Map,
  MapPin,
  Navigation as NavigationIcon,
  Navigation2,
  Compass,
  Globe,
  Globe2,
} from 'lucide-react';

// ── Data / Analytics ──────────────────────────────────────────────────────────
export {
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  Table as TableIcon,
  LayoutGrid,
  LayoutList,
  List,
  Grid as GridIcon,
  Grid2X2,
  Grid3X3,
} from 'lucide-react';

// ── User / People ─────────────────────────────────────────────────────────────
export {
  User,
  User2,
  Users,
  Users2,
  UserCheck,
  UserX,
  Contact,
  Building,
  Building2,
} from 'lucide-react';

// ── Time ──────────────────────────────────────────────────────────────────────
export {
  Clock,
  Clock1,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  Timer,
  Hourglass,
} from 'lucide-react';

// ── Device / Tech ─────────────────────────────────────────────────────────────
export {
  Monitor,
  Laptop,
  Tablet,
  Smartphone,
  Keyboard,
  Mouse,
  Printer,
  Server,
  Cpu,
  HardDrive,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryLow,
  Power,
  Plug,
  Code,
  Code2,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
} from 'lucide-react';

// ── Misc ──────────────────────────────────────────────────────────────────────
export {
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Zap,
  Flame,
  Snowflake,
  Leaf,
  Flower,
  TreePine,
  Tag as TagIcon,
  Tags,
  Flag,
  Layers,
  Layout as LayoutIcon,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Sidebar,
  SidebarOpen,
  SidebarClose,
  Columns,
  Rows,
  ToggleLeft,
  ToggleRight,
  Sliders,
  Palette,
  Paintbrush,
  Scissors,
  Crop,
  ZoomIn,
  ZoomOut,
  Move,
  Grab,
  GripVertical,
  GripHorizontal,
} from 'lucide-react';
